# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestKeypresses():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_keypresses(self):
    self.driver.get("https://the-internet.herokuapp.com/")
    self.driver.set_window_size(932, 903)
    self.driver.find_element(By.LINK_TEXT, "Key Presses").click()
    self.driver.find_element(By.ID, "target").click()
    self.driver.find_element(By.ID, "target").send_keys("t")
    assert self.driver.find_element(By.ID, "result").text == "You entered: T"
    self.driver.find_element(By.ID, "target").send_keys("e")
    assert self.driver.find_element(By.ID, "result").text == "You entered: E"
    self.driver.find_element(By.ID, "target").send_keys("s")
    assert self.driver.find_element(By.ID, "result").text == "You entered: S"
    self.driver.find_element(By.ID, "target").send_keys("t")
    assert self.driver.find_element(By.ID, "result").text == "You entered: T"
    self.driver.find_element(By.ID, "target").send_keys(Keys.ENTER)
    self.driver.close()
  
